# Generated by Django 2.0.1 on 2018-12-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20181217_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('-id',)},
        ),
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
    ]
